/*
 * This Java source file was generated by the Gradle 'init' task.
 */

import game.Game;

public class AppMain {

    public static void main(String[] args) {
        Game.gameInstance().beginGame();
    }

}
